### ISSUE TITLE
Problems with inclusion

### ISSUE THREAD

**Issue by physiker123** [vosmont/Vera-Plugin-ZiGateGateway#5]
Hello, I just bought a zigate and I have troubles to get it work with my veraplus. 
What I did: 
- Assemble the kit 
- Test the kit with an windows computer (worked, it showed data from a tradfri controller (the 5 button), did not do firmware update, since I bought it last week) 
- Vera: deactivated usb logs -
 Plug it into my vera, did the modifications and uploaded the luup files.
 - configured the serial port (it was recognized)
 - enabled debug mode 

And now it does not recognize neither the e27 1000lm tradfri lamp nor the telecommand. I tried every possible way, also this one: http://faire-ca-soi-meme.fr/zigate/2017/11/27/maitrisez-vos-ampoules-zigbee/

 I saw the flickering of the lamp, but the blue light of the zigate always stays on. 

The log shows in inclusion mode: 
50 11/06/18 16:15:33.143 luup_log:810: (ZiGateGateway::handleCommand) Get handler for command 'getDevicesInfos' 
50 11/06/18 16:15:33.143 luup_log:810: (ZiGateGateway::handleCommand.getDevicesInfos) Get device list 

and so on. 

Only one time I got this message using the telecommand: 

02 11/06/18 15:52:43.140 luup_log:810: (ZiGateGateway::Network.receive) Unknown message type 0x004D
 02 11/06/18 15:52:43.145 luup_log:810: (ZiGateGateway::Network.receive) Unknown message type 0x004D
 02 11/06/18 15:52:43.156 luup_log:810: (ZiGateGateway::Network.receive) Unknown message type 0x8701 
50 11/06/18 15:52:44.348 luup_log:810: (ZiGateGateway::handleCommand) Get handler for command 'getDevicesInfos' 
50 11/06/18 15:52:44.349 luup_log:810: (ZiGateGateway::handleCommand.getDevicesInfos) Get device list 
50 11/06/18 15:52:47.365 luup_log:810: (ZiGateGateway::handleCommand) Get handler for command 'getDevicesInfos' 
50 11/06/18 15:52:47.365 luup_log:810: (ZiGateGateway::handleCommand.getDevicesInfos) Get device list 
50 11/06/18 15:52:50.391 luup_log:810: (ZiGateGateway::handleCommand) Get handler for command 'getDevicesInfos' 
50 11/06/18 15:52:50.392 luup_log:810: (ZiGateGateway::handleCommand.getDevicesInfos) Get device list 
50 11/06/18 15:52:53.423 luup_log:810: (ZiGateGateway::handleCommand) Get handler for command 'getDevicesInfos' 
50 11/06/18 15:52:53.424 luup_log:810: (ZiGateGateway::handleCommand.getDevicesInfos) Get device list 
50 11/06/18 15:52:56.450 luup_log:810: (ZiGateGateway::handleCommand) Get handler for command 'getDevicesInfos' 
50 11/06/18 15:52:56.450 luup_log:810: (ZiGateGateway::handleCommand.getDevicesInfos) Get device list 
02 11/06/18 15:52:59.415 luup_log:810: (ZiGateGateway::Network.receive) Unknown message type 0x8048 

the blue light was turning off and on, but then nothing... Do you have any clue? 

Thank you in advance, Jens

**Comment by physiker123** [comment]
Hello!

With the development branch, the blue light is blinking in inclusion mode. So far so good :)

Problem: It still does not include the devices (in this case the telecommand). But I'm closer, the logs:

> 08	11/07/18 9:07:09.966	JobHandler_LuaUPnP::HandleActionRequest device: 810 service: urn:upnp-org:serviceId:ZiGateGateway1 action: Inclusion <0x6a21a520>
> 08	11/07/18 9:07:09.966	JobHandler_LuaUPnP::HandleActionRequest argument serviceId=urn:upnp-org:serviceId:ZiGateGateway1 <0x6a21a520>
> 50	11/07/18 9:07:09.967	luup_log:810: (ZiGateGateway::Main.startInclusion)          Permit joining during 30 secondes <0x6a21a520>
> 50	11/07/18 9:07:09.968	luup_log:810: (ZiGateGateway::Network.send)                 (type:0x0049), (payload:FFFC1E) <0x6a21a520>
> 50	11/07/18 9:07:09.969	luup_log:810: (ZiGateGateway::Network.flush)                Send message: 01-02-10-49-02-10-02-13-57-FF-FC-1E-03 <0x6a21a520>
> 50	11/07/18 9:07:09.976	luup_log:810: (ZiGateGateway::Network.receive)              (status:Success), (sqn:43) <0x6a01a520>
> 01	11/07/18 9:07:19.482	LuaInterface::CallFunction-2 lu_incoming failed [string "--[[..."]:1556: arithmetic overflow <0x6a01a520>
> 01	11/07/18 9:07:23.640	LuaInterface::CallFunction-2 lu_incoming failed [string "--[[..."]:1556: arithmetic overflow <0x6a01a520>
> 01	11/07/18 9:07:23.720	LuaInterface::CallFunction-2 lu_incoming failed [string "--[[..."]:1556: arithmetic overflow <0x6a01a520>
> 50	11/07/18 9:07:23.730	luup_log:810: (ZiGateGateway::Network.receive)              Router Discover: (status:Success), (networkStatus:0) <0x6a01a520>
> 02	11/07/18 9:07:37.192	luup_log:810: (ZiGateGateway::Network.receive)              Unknown message (type:0x8048), (payload:90-FD-9F-FF-FE-FA-B5-51-00) <0x6a01a520>


It seems that there is an overflow... Do you have a clue?

THank you!

**Comment by physiker123** [comment]
I just did a little bit of debugging, the problem persists.
The problem occurs with an ikea lightbulb and the telecommand. 

I cannot really print the strData. But obviously, the division of the string has a wrong format or wants to take action where no data is. Would it be possible to send you more extended logs, or are there more extended logs?

Thank you!

**Comment by vosmont** [comment]
The problem with arithmetic overflow should be fixed with the version 1.2 (development).

The way to retrieve the equipment id (IEEE adress) has been changed : you will have to delete and recreate all the linked devices.

**Comment by physiker123** [comment]
Hi,

thank you! Now I can see the discovered devices in the tab, so far so good!

Another problem -.-

I cannot learn the devices, because the buttons are missing :)

See here:

![bildschirmfoto 2018-11-09 um 08 08 27](https://user-images.githubusercontent.com/44749710/48248394-6d00db00-e3f7-11e8-8867-fe44271d6804.png)
![bildschirmfoto 2018-11-09 um 08 08 18](https://user-images.githubusercontent.com/44749710/48248395-6d997180-e3f7-11e8-8cd4-110ab0878b5c.png)


And: the language file is missing again:

![bildschirmfoto 2018-11-09 um 08 14 47](https://user-images.githubusercontent.com/44749710/48248441-9ae61f80-e3f7-11e8-98e9-b5d3b77402be.png)


I would be happy to help with the development if needed, but until now I am trying to understand the code :)

**Comment by vosmont** [comment]
For the moment, the inclusion is just for discovering the "enclosure" of the equipment.
The plugin does not find the features of the equipment by itself.

You must operate the equipment to trigger messages that will allow the plugin to see its features.

Tell me if it fixes the issue.

**Comment by physiker123** [comment]
Well, I see your point.

There are 3 things I do not understand:

1.) The language file. I saw the changes you made, and the error posted above persists if I do not add the -de file. Strange thing is, that I do not see why your changes provoke this error..

2.) I got an error, see here:

![bildschirmfoto 2018-11-09 um 23 09 43](https://user-images.githubusercontent.com/44749710/48290939-eb4f9280-e474-11e8-85ec-bc2a19e9e570.png)

3.) I cannot get the features discovered by the plugin. I see your point, so I did the following:

- Put zigate in inclusion mode
- Push inclusion button on telecommand 4 times
- the device announcement appears in the logs
- Pushing buttons on telecommand to make them appear in the features, but they do not appear. I get the following message (I think zigate does not understand something in the message):

![bildschirmfoto 2018-11-09 um 23 10 37](https://user-images.githubusercontent.com/44749710/48291096-74ff6000-e475-11e8-8837-7cc93d1aa132.png)

- I also tried http://faire-ca-soi-meme.fr/zigate/2017/11/27/maitrisez-vos-ampoules-zigbee/ , but no success. I also cannot see, how I make the features of my lightbulb (on/off, dimming) discover, because I cannot trigger them without integrating into a zigbee network (?)

Sorry for causing so much trouble :)

**Comment by vosmont** [comment]
Hello,

1.) This error is not really an error : Vera just says that the file does not exist.
How have you delete the "-de" file ? (it's not possible to do this from the standard UI)

2.) Should be fixed

3.) It won't work better.. but the logs should be more clear with the new version 1.3. Can you test ?

**Comment by physiker123** [comment]
Hi,

I just updated, now I get this, and I still cannot "learn" the devices to include them into my vera (at least my telecommand, I will test the lamp later), so I cannot really use them...


Here is the log: 
![bildschirmfoto 2018-11-13 um 10 26 07](https://user-images.githubusercontent.com/44749710/48403645-a5bdee80-e72e-11e8-9a12-890629d3f1b1.png)

![bildschirmfoto 2018-11-13 um 10 26 19](https://user-images.githubusercontent.com/44749710/48403660-ab1b3900-e72e-11e8-98f7-9349f1e0e302.png)

Best regards,

jens

**Comment by physiker123** [comment]
Just a question: With what kind of devices do you use the zigate? So which device is working with your version of the plugin?

**Comment by vosmont** [comment]
Hello @physiker123,

I'm still working on the plugin, but I think there are bad news for you : it seems that, for the moment, the ZiGate is not able to handle the Tradfri remote.

https://github.com/fairecasoimeme/ZiGate/issues/64
https://github.com/fairecasoimeme/ZiGate/issues/65

Anyway, I'm using the ZiGate with Xiaomi sensors (Cube, Button, Occupency, Pressure) and it works very well.

**Comment by physiker123** [comment]
Hey,

no problem, I will just return the remote.

I tried my zigate under domoticz, and I was able to add my lightbulb and control it. I think I will add my devices via domoticz, the pairing was working..

Thank you anyway :)

**Comment by pipiche38** [comment]
I beleive this issue can be closed
